default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  password: password
  port: 5432
  host: db
  socket: /tmp/sockets/
  database: docker_suggests_development
test:
  <<: *default
  username: postgres
  password: password
  port: 5432
  host: db
  socket: /tmp/sockets/
  database: docker_suggests_test
production:
  <<: *default
  database: docker_suggests_production
  username: docker_suggests
  password: <%= ENV['PARTS_DIVICE_DATABASE_PASSWORD'] %>
