version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=suggests_and_projects"
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/docker_from_compose
    env_file:
      - ".env.dev"
    ports:
      - "3000:3000"
    depends_on:
      - db
    # テスト実行する時にchromeコンテナが自動で起動する
      - chrome
    # stdin_open: true
    # tty: true
  chrome:
    image: selenium/standalone-chrome:latest
    # image: selenium/standalone-chrome-debug:latest
    ports:
      - 4444:4444
      # - 5900:5900
