version: 2
jobs: # step
  build: # as a entry point
    parallelism: 3
    docker:
      - image: circleci/ruby:2.6.5-node-browsers # e2e test
        environment: # プライマリ コンテナの環境変数
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: postgres
          RAILS_ENV: test
          RACK_ENV: test
      - image: circleci/postgres:13
        environment: # データベースの環境変数
          POSTGRES_USER: postgres
          POSTGRES_DB: docker_suggests_test
          POSTGRES_PASSWORD: password
    working_directory: ~/dic_issue_graduate
    steps:
      - checkout
      #bundle キャッシュを復元
      - restore_cache:
          # name: Restore bundle cache
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      # bundle install で依存関係をインストール
      - run:
          name: install dependencies
          command: gem install bundler -v 2.1.4
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      # Ruby の依存関係のバンドル キャッシュを保存
      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
      - run:
          name: wait untill db up
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 120s
      - run: bundle exec rake db:create RAILS_ENV=test
      - run: bundle exec rake db:schema:load RAILS_ENV=test
      - run:
          name: run tests
          command: bundle exec rspec
    # deploy:
    #   docker:
    #     - image: circleci/ruby:2.6.5-node-browsers
    #       environment:
    #         BUNDLER_VERSION: 2.1.4
    #   steps:
    #     - checkout
    #     - ruby/install-deps
    #     - add_ssh_keys:
    #         fingerprints:
    #           - "92:38:33:e6:f7:08:e2:f3:8f:49:1e:1f:88:d1:2f:a1"
    #     - deploy:
    #         name: capistrano deploy
    #         command: bundle exec cap production deploy
    #
    # workflows:
    #   version: 2
    #   build_accept_deploy:
    #     jobs:
    #       - build
    #       - deploy:
    #           requires:
    #             - build
    #           filters:
    #             branches:
    #               only: cd_ci
      - add_ssh_keys:
          fingerprints:
            - "92:38:33:e6:f7:08:e2:f3:8f:49:1e:1f:88:d1:2f:a1"
      - run:
          name: add ssh-agent
          command: |
            ssh-agent -s > ~/.ssh_agent_conf
            source ~/.ssh_agent_conf
            chmod -R 700 ${HOME}
            for _k in $(ls ${HOME}/.ssh/id*); do
              ssh-add ${_k} || true
            done
            cat <<EOF >> ${HOME}/.ssh/config
              Host github github.com
              IdentityFile ~/.ssh/id_rsa_923833e6f708e2f38f491e1f88d12fa1
              User sec_il_n
            EOF
      - deploy:
          name: capistrano deploy
          command: |
            if [ "${CIRCLE_BRANCH}" != "cd_ci" ]; then
              exit 0
            fi
            bundle exec cap production deploy --trace
# https://qiita.com/dich1/items/67cad8fa072c61a89c83
